[project]
site_name = "Karsk"
site_description = "Tool for building and deploying software on HPC clusters"
repo_url = "https://github.com/equinor/karsk"

docs_dir = "docs"
site_dir = "site"

nav = [
  { "Home" = "index.md" },
  { "Getting started" = "getting-started.md" },
  { "Concepts" = "concepts.md" },
  { "Commands" = [
    { "Common options" = "commands/common-options.md" },
    { "karsk build" = "commands/build.md" },
    { "karsk build-wrapper" = "commands/build-wrapper.md" },
    { "karsk enter" = "commands/enter.md" },
    { "karsk init" = "commands/init.md" },
    { "karsk install" = "commands/install.md" },
    { "karsk schema" = "commands/schema.md" },
    { "karsk sync" = "commands/sync.md" },
    { "karsk test" = "commands/test.md" },
  ] },
  { "API Reference" = [
    { "karsk.config" = "api/config.md" },
    { "karsk.context" = "api/context.md" },
  ] },
]

[project.theme.icon]
logo = "lucide/coffee"

[project.markdown_extensions.admonition]

[project.markdown_extensions.pymdownx.details]

[project.markdown_extensions.pymdownx.superfences]

[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true

[project.markdown_extensions.pymdownx.snippets]
base_path = ["."] # relative to project root

[project.plugins.mkdocstrings.handlers.python]
paths = ["src"]

[project.plugins.mkdocstrings.handlers.python.options]
extensions = ["griffe_pydantic"]
